[project]
name = "onert"
version = "0.2.0"
requires_python = ">= 3.8"
description = "onert API binding"
license = "MIT"
dependencies = [
    "numpy"
]

[project.urls]
Homepage = "https://github.com/Samsung/ONE"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
"include" = ["onert"]

[tool.hatch.build.targets.wheel.hooks.custom]
"path" = "wheel_target_hook.py"
