name: Run ONERT Android Release Build

on:
  push:
    branches:
      - master
      - release/*
    paths:
      - '.github/workflows/run-onert-android-build.yml'
      - 'nnfw'
      - 'Makefile.template'
      - 'runtime/**'
      - '!runtime/contrib/**'
      - '!runtime/infra/debian/**'
      - '!runtime/infra/gbs/**'
      - '!runtime/infra/python/**'
      - '!**/*.md'
  pull_request:
    branches:
      - master
      - release/*
    paths:
      - '.github/workflows/run-onert-android-build.yml'
      - 'nnfw'
      - 'Makefile.template'
      - 'runtime/**'
      - '!runtime/contrib/**'
      - '!runtime/infra/debian/**'
      - '!runtime/infra/gbs/**'
      - '!runtime/infra/python/**'
      - '!**/*.md'

defaults:
  run:
    shell: bash

# Cancel previous running jobs when pull request is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository_owner == 'Samsung'
    runs-on: one-x64-linux
    container:
      image: samsungonedev.azurecr.io/nnfw/one-devtools:android-sdk
      options: --user root
    env:
      TARGET_ARCH: aarch64
      TARGET_OS: android
      CROSS_BUILD: 1
      BUILD_TYPE: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore onecc external cache
        uses: actions/cache/restore@v4
        with:
          path: externals
          key: external-onecc-${{ hashFiles('infra/cmake/packages/**/*.cmake') }}
          restore-keys: |
            external-onecc-

      - name: Restore externals cache
        uses: actions/cache/restore@v4
        id: cache-externals
        with:
          path: runtime/externals
          key: external-onert-ndk-${{ hashFiles('runtime/infra/cmake/packages/**/*.cmake') }}
          restore-keys: |
            external-onert-ndk-

      - name: Restore ccache cache
        uses: actions/cache/restore@v4
        id: cache-ccache
        with:
          path: ~/.cache/ccache
          key: ccache-onert-android-${{ github.sha }}
          restore-keys: |
            ccache-onert-android

      # Set ccache size
      # Release < 100MB / Debug < 250MB
      - name: Reduce ccache size
        run: ccache -M 100MB

      # numpy: test build
      # scons: arm compute library build
      - name: Install packages
        run: |
          pip3 install numpy
          sudo apt-get update && sudo apt-get -qqy install scons

      # Use NDK Default - path set by containe envrionment variable
      - name: Build onert
        run: |
          make -f Makefile.template

      # Save cache on push to reduce the size of cache storage
      #   ccache cache: only for master branch
      #   externals cache: only for master branch
      - name: Save ccache cache
        uses: actions/cache/save@v4
        if: github.event_name == 'push' && github.ref_name == 'master'
        with:
          path: ~/.cache/ccache
          key: ${{ steps.cache-ccache.outputs.cache-primary-key }}

      - name: Save externals cache
        uses: actions/cache/save@v4
        if: github.event_name == 'push' && github.ref_name == 'master'
        with:
          path: runtime/externals
          key: ${{ steps.cache-externals.outputs.cache-primary-key }}
